# Generated by Django 4.2.29 on 2026-03-06 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_study",
                        to="simulation.run",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_studies",
                        to="simulation.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Case studies",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudySection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True)),
                (
                    "source_refs",
                    models.JSONField(
                        default=list,
                        help_text="Pointers to run steps/events/metrics used",
                    ),
                ),
                ("is_auto_generated", models.BooleanField(default=True)),
                (
                    "case_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cases.casestudy",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "unique_together": {("case_study", "key")},
            },
        ),
    ]
